name = "tahsilat-system"
main = "src/worker.js"
compatibility_date = "2026-06-30"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "tahsilat-db"
database_id = "7f3509ae-f3ab-41fc-97bf-65543974d081"
